spring.application.name=claims-records-api

spring.datasource.url=jdbc:postgresql://localhost:5432/claims_api
spring.datasource.username=bokufitness
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
